name = "yacht-router"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [
    { binding = "AUTH_STORE", id = "91aeb1425b6c4a0e9c8a5cda05f3755a" },
    { binding = "YACHT_USERS", id = "c8ffbbf3c0634098818d7617cedd12f8" }
]

[vars]
AUTH0_DOMAIN = "https://dev-seokmin.us.auth0.com"
AUTH0_CLIENT_ID = "oEKdGffuHxeSYn9aj68hNIDBBABBgX9w"
ROUTE_DOMAIN = "https://yacht.seokmin.dev"

[build]
command = "yarn install && yarn build"
[build.upload]
format = "modules"
main = "./worker.mjs"
