name = "yacht-auth"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

kv_namespaces = [
    { binding = "AUTH_STORE", id = "91aeb1425b6c4a0e9c8a5cda05f3755a" }
]

[vars]
AUTH0_DOMAIN = "https://dev-seokmin.us.auth0.com"
AUTH0_CLIENT_ID = "oEKdGffuHxeSYn9aj68hNIDBBABBgX9w"
PAGE_DOMAIN = "https://edge-yacht.pages.dev"

[build]
command = "yarn install && yarn build"
[build.upload]
format = "modules"
main = "./worker.mjs"
