name = "yacht-api"
type = "javascript"
zone_id = ""
account_id = ""
route = ""
workers_dev = true

[build]
command = "yarn install && yarn build"
[build.upload]
format = "modules"
main = "./worker.js"

[durable_objects]
bindings = [
#    { name = "yachtGame", class_name = "YachtGame" }
    {name = "hello", class_name = "Hello"}
]

#[[migrations]]
#tag = "v1"
#new_classes = ["YachtGame"]
