name: Publish page

on:
  push:
    branches: [main]
    paths:
      - packages/www/**
      - packages/shared/**
      - .github/workflows/publish-page.yml

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Run deploy hooks
        id: api
        run: |
          curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK }}"
