name: Publish page

on:
  push:
    branches: [main]
    paths:
      - packages/www/**
      - packages/shared/**
      - .github/workflows/publish-page.yml

jobs:
  publish:
    name: Publish to Cloudflare Pages
    runs-on: ubuntu-latest
    steps:
      - name: Deploy pages
        uses: SeokminHong/pages-action@v0.2
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: edge-yacht
          email: ${{ secrets.CLOUDFLARE_EMAIL }}
          authKey: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
